/** Shared visual tokens for modal components (matches admin UI). */
export const modalStyles = {
    overlay: {
        position: "fixed",
        inset: 0,
        background: "rgba(0,0,0,0.7)",
        display: "flex",
        alignItems: "center",
        justifyContent: "center",
        zIndex: 100,
    },
    modal: {
        background: "#111118",
        border: "1px solid #1e2030",
        borderRadius: "16px",
        padding: "32px",
        width: "100%",
        maxWidth: "440px",
        boxSizing: "border-box",
    },
    modalTitle: {
        color: "#f0f4ff",
        fontSize: "18px",
        fontWeight: "700",
        margin: "0 0 20px",
    },
    modalTitleDanger: {
        color: "#ef4444",
    },
    bodyText: {
        color: "#8892b0",
        fontSize: "14px",
        lineHeight: "1.6",
        margin: 0,
    },
    code: {
        background: "#0a0a0f",
        border: "1px solid #1e2030",
        borderRadius: "4px",
        padding: "2px 8px",
        fontSize: "12px",
        color: "#60a5fa",
        fontFamily: "monospace",
    },
    modalForm: {
        display: "flex",
        flexDirection: "column",
        gap: "12px",
    },
    label: {
        color: "#4a5180",
        fontSize: "12px",
        fontWeight: "600",
        textTransform: "uppercase",
        letterSpacing: "0.5px",
    },
    input: {
        background: "#0d0d14",
        border: "1px solid #1e2030",
        borderRadius: "8px",
        padding: "11px 14px",
        color: "#f0f4ff",
        fontSize: "14px",
        outline: "none",
    },
    select: {
        background: "#0d0d14",
        border: "1px solid #1e2030",
        borderRadius: "8px",
        padding: "11px 14px",
        color: "#f0f4ff",
        fontSize: "14px",
        outline: "none",
    },
    error: {
        color: "#ef4444",
        fontSize: "13px",
        margin: 0,
    },
    modalActions: {
        display: "flex",
        gap: "10px",
        marginTop: "8px",
    },
    cancelBtn: {
        flex: 1,
        background: "none",
        border: "1px solid #1e2030",
        borderRadius: "8px",
        color: "#4a5180",
        padding: "11px",
        fontSize: "14px",
        cursor: "pointer",
    },
    saveBtn: {
        flex: 1,
        background: "linear-gradient(135deg, #0ea5e9, #2563eb)",
        border: "none",
        borderRadius: "8px",
        color: "#fff",
        padding: "11px",
        fontSize: "14px",
        fontWeight: "700",
        cursor: "pointer",
    },
    confirmBtn: {
        flex: 1,
        background: "linear-gradient(135deg, #0ea5e9, #2563eb)",
        border: "none",
        borderRadius: "8px",
        color: "#fff",
        padding: "11px",
        fontSize: "14px",
        fontWeight: "700",
        cursor: "pointer",
    },
    deleteBtnModal: {
        flex: 1,
        background: "#1a0a0a",
        border: "1px solid #ef4444",
        borderRadius: "8px",
        color: "#ef4444",
        padding: "11px",
        fontSize: "14px",
        fontWeight: "700",
        cursor: "pointer",
    },
    not_allowed: {
        cursor: "not-allowed",
    }
};
